"""Theming.

Context is themed the way the rest of a Hyprland session is: it ships one
stylesheet, and `$XDG_CONFIG_HOME/context/style.css` loads over it — the same
contract as waybar's or swaync's style.css, so the file can be written by hand
or generated by whatever templates the rest of the desktop's colours.

Every colour is published as a `@define-color ctx_*` name and the built-in
rules only ever reference the names, so redefining a few of them recolours the
whole launcher; any ordinary CSS rule in the file styles widgets directly, at
higher priority than the built-in stylesheet. Context also draws things CSS
cannot reach — the app grid's tiles, the layout preview — so it parses the
`@define-color ctx_*` lines out of style.css itself and feeds the same values
to Cairo. The file is watched: saving it restyles the running launcher.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, fields, replace
from pathlib import Path

from context.system.logging_setup import get_logger

log = get_logger("theme")

ENV_STYLE = "CONTEXT_STYLE"


def config_dir() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or (Path.home() / ".config")
    return Path(base) / "context"


def style_path() -> Path:
    """The stylesheet the user owns, and the one "write the style file" writes."""
    override = os.environ.get(ENV_STYLE)
    return Path(override) if override else config_dir() / "style.css"


def style_paths() -> list[Path]:
    """Every stylesheet, in the order they are loaded. The last one wins.

    The same chain the settings follow, for the same reason: a NixOS module
    declares a look in /etc/xdg and the user's own file still overrides it. CSS
    needs no merging rule of its own — a later `@define-color` redefinition
    beats an earlier one, which is the behaviour the whole theming contract
    already rests on.
    """
    override = os.environ.get(ENV_STYLE)
    if override:
        return [Path(override)]
    from context.state.settings import system_dirs

    found = [directory / "context" / "style.css" for directory in reversed(system_dirs())]
    found.append(config_dir() / "style.css")
    return found


def style_text() -> str:
    """Every stylesheet that exists, concatenated in load order."""
    parts = []
    for path in style_paths():
        try:
            parts.append(path.read_text())
        except FileNotFoundError:
            continue
        except OSError as exc:
            log.warning("ignoring %s: %s", path, exc)
    return "\n".join(parts)


# One definition per palette entry, tolerant of whatever spacing the file uses.
# Only ctx_* names are Context's to read; a style.css shared with other tools
# may define colours that are not.
_DEFINE = re.compile(r"@define-color\s+ctx_(\w+)\s+([^;\n]+);")


def _rgba(value: str, fallback: tuple[float, float, float, float]):
    """Parse #rgb, #rrggbb, #rrggbbaa, rgb() or rgba() into floats for Cairo."""
    text = value.strip()
    functional = re.fullmatch(r"rgba?\(([^)]*)\)", text)
    if functional:
        parts = [p.strip() for p in functional.group(1).split(",")]
        if len(parts) not in (3, 4):
            return fallback
        try:
            channels = [int(p) / 255 for p in parts[:3]]
            alpha = float(parts[3]) if len(parts) == 4 else 1.0
        except ValueError:
            return fallback
        return (*channels, alpha)

    text = text.lstrip("#")
    try:
        if len(text) == 3:
            parts = [int(c * 2, 16) for c in text]
        elif len(text) in (6, 8):
            parts = [int(text[i : i + 2], 16) for i in range(0, len(text), 2)]
        else:
            return fallback
    except ValueError:
        return fallback
    values = [p / 255 for p in parts]
    while len(values) < 4:
        values.append(1.0)
    return tuple(values[:4])


@dataclass(frozen=True)
class Theme:
    """Colours, as CSS colour strings so style.css and Cairo read the same."""

    accent: str = "#5ac0c0"
    # The card every Context surface is drawn as. Transparency lives here:
    # give it an alpha — `rgba(30, 30, 30, 0.75)` or `#1e1e1ebf` — and the
    # desktop shows through, the same way a bar's stylesheet does it. The
    # window behind the card is transparent already, and nothing else paints
    # the full surface, so the alpha is not compounded.
    surface: str = "#1e1e1e"
    on_surface: str = "#ffffff"

    # Drawn under the surface: the card a group of settings sits on, the line
    # between rows, and the shade a control uses to lift off the background.
    card: str = "#ffffff0d"
    border: str = "#ffffff1a"
    control: str = "#ffffff14"
    control_hover: str = "#ffffff26"

    # Layout preview
    preview_background: str = "#00000047"
    slot_fill: str = "#5ac0c052"
    slot_fill_active: str = "#5ac0c080"
    slot_border: str = "#5ac0c0b3"

    # App grid
    tile_background: str = "#ffffff10"
    tile_hover: str = "#ffffff1f"
    tile_selected: str = "#5ac0c038"

    # The screen a dragged window would land on, and the window on its way out.
    drop_target: str = "#5ac0c024"
    leaving_border: str = "#5ac0c0"

    # Collapsed sidebar. Saved contexts recede, open ones are lit, and the one
    # you are in is ringed — three states that differ in more than shade.
    rail_background: str = "#ffffff08"
    rail_hover: str = "#ffffff24"
    rail_open: str = "#5ac0c033"
    rail_active: str = "#5ac0c059"
    rail_divider: str = "#ffffff26"

    @classmethod
    def load(cls) -> "Theme":
        """The defaults, plus any `@define-color ctx_*` overrides in style.css.

        Only the definitions are read here — the rest of the file is CSS and
        belongs to GTK. A missing or unreadable file means the defaults; a
        garbled line means that line and nothing more.
        """
        legacy = config_dir() / "theme.json"
        if legacy.exists():
            log.warning(
                "theme.json is no longer read; colours now come from %s",
                style_path(),
            )

        text = style_text()
        if not text.strip():
            return cls()

        known = {f.name for f in fields(cls)}
        values = {}
        for name, value in _DEFINE.findall(text):
            if name in known:
                values[name] = value.strip()
            else:
                log.debug("style.css defines unknown colour ctx_%s", name)
        return replace(cls(), **values)

    def write_template(self) -> Path:
        """Write style.css with every colour spelled out, ready to edit."""
        path = style_path()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "/* Context's colours. Redefine any of these, or add ordinary CSS\n"
            "   rules — this file loads over the built-in stylesheet, the way\n"
            "   waybar's style.css does. Saving it restyles the running\n"
            "   launcher. */\n\n" + self._defines() + "\n"
        )
        return path

    def rgba(self, name: str):
        """One colour as an (r, g, b, a) tuple, for Cairo."""
        default = getattr(Theme(), name, "#ffffff")
        return _rgba(getattr(self, name, default), _rgba(default, (1, 1, 1, 1)))

    def _defines(self) -> str:
        lines = [
            f"@define-color ctx_{f.name} {getattr(self, f.name)};" for f in fields(self)
        ]
        # The surface with its transparency taken off, for the views that cover
        # the whole screen. Derived rather than declared, so a style.css that
        # sets one translucent colour gets both — and it can still be named
        # outright, since a redefinition in that file wins over this.
        red, green, blue, _alpha = self.rgba("surface")
        lines.append(
            "@define-color ctx_surface_solid "
            f"rgb({round(red * 255)}, {round(green * 255)}, {round(blue * 255)});"
        )
        return "\n".join(lines)

    def css(self) -> bytes:
        """The built-in stylesheet.

        Rules reference the `@ctx_*` names rather than inlining values, so a
        redefinition in style.css reaches every rule that uses the colour.
        """
        return (self._defines() + _NAMED_COLORS + _RULES).encode()


# GTK's own named colours, redefined onto the palette.
#
# Setting `gtk-theme-name` or GTK_THEME does not help: the stylesheet is
# already resolved by the time an application can ask, so `theme_bg_color`
# stayed at the desktop theme's value regardless. Every widget Context does not
# name a colour for — scrollbars, popovers, tooltips, menus — reads these, so
# redefining them is what keeps the desktop theme's furniture off Context's
# windows. Measured, not assumed: overriding the names moves the computed
# colour, overriding the setting does not. */
_NAMED_COLORS = """
@define-color theme_bg_color @ctx_surface;
@define-color theme_fg_color @ctx_on_surface;
@define-color theme_base_color @ctx_card;
@define-color theme_text_color @ctx_on_surface;
@define-color theme_selected_bg_color @ctx_accent;
@define-color theme_selected_fg_color @ctx_surface;
@define-color insensitive_bg_color @ctx_surface;
@define-color insensitive_fg_color alpha(@ctx_on_surface, 0.5);
@define-color borders @ctx_border;
@define-color window_bg_color @ctx_surface;
@define-color window_fg_color @ctx_on_surface;
@define-color view_bg_color @ctx_card;
@define-color view_fg_color @ctx_on_surface;
@define-color headerbar_bg_color @ctx_card;
@define-color headerbar_fg_color @ctx_on_surface;
@define-color popover_bg_color @ctx_card;
@define-color popover_fg_color @ctx_on_surface;
@define-color accent_bg_color @ctx_accent;
@define-color accent_color @ctx_accent;
"""

_RULES = """
/* Popovers are children of the root, not of the window, so a rule scoped to
   `.ctx-window` never reaches a dropdown's list. */
popover > contents,
popover > arrow {
    background-color: @ctx_card;
    color: @ctx_on_surface;
}

/* The style classes libadwaita used to define.

   Removing its widgets left these behind on widgets all over Context —
   `boxed-list` on every list, `dim-label` on every section heading — with
   nothing defining them any more. They did not fail loudly: the list simply
   fell back to the desktop theme's dark card, and the headings kept an opacity
   that made them invisible on a light surface. Defining them here is what
   finishes the removal. */
.boxed-list {
    background-color: @ctx_card;
    border: 1px solid @ctx_border;
    border-radius: 12px;
}
.boxed-list > row {
    background: transparent;
    border-bottom: 1px solid @ctx_border;
}
.boxed-list > row:last-child {
    border-bottom: none;
}

.dim-label {
    opacity: 0.7;
}

.heading {
    font-weight: bold;
}
.title-4 {
    font-weight: bold;
    font-size: 1.1em;
}

/* Flat buttons carry no plate until pointed at — used for the icon buttons
   that sit inside rows, where a full button would be noise. */
button.flat {
    background: none;
    background-image: none;
    border-color: transparent;
    box-shadow: none;
}
button.flat:hover {
    background-color: @ctx_control_hover;
}

button.suggested-action {
    background-image: none;
    background-color: @ctx_accent;
    color: @ctx_surface;
    border-color: @ctx_accent;
}
button.destructive-action {
    background-image: none;
    background-color: #c01c28;
    color: #ffffff;
    border-color: #c01c28;
}

/* The context you are in, marked the way a browser marks the current tab.
   Placed after the blanket foreground rule above so it is not overridden by
   it, and matched on descendants too since the row's labels are children. */
.accent,
.accent label,
window.ctx-window .accent,
window.ctx-window .accent label {
    color: @ctx_accent;
}

/* Context draws its own surfaces rather than inheriting a desktop theme's.
   This is the part libadwaita made impossible: it resolves light and dark from
   the system preference before an application gets a say, so a stylesheet like
   this one was always painting over widgets that had already chosen. */
window.ctx-window {
    background-color: transparent;
    color: @ctx_on_surface;
}

/* Every Context surface is dressed as a window: the compositor draws windows
   with rounded corners and gaps, and a square launcher flush against the edge
   read as a foreign object next to them. The window itself is transparent and
   this card, floated off the edges by layer-shell margins, is what shows. The
   radius is the compositor's rounding plus its border width. */
.ctx-surface {
    background-color: @ctx_surface;
    /* An inset ring rather than a border: a border is layout and would raise
       the rail's minimum width by its two edges; a shadow only draws. */
    box-shadow: inset 0 0 0 2px @ctx_border;
    border-radius: 10px;
}

/* A view that covers the whole screen is opaque, whatever the surface's alpha
   says. Transparency is for a strip at the edge, where seeing what is behind
   it is the point; spread over the entire output it is a haze between the user
   and what they are reading. */
.ctx-surface.ctx-solid {
    background-color: @ctx_surface_solid;
}

/* Text colour has to reach every descendant, not just direct children.
   `> *` left the section headings ("Open", "Saved") several levels down still
   wearing the desktop theme's light-on-dark foreground, which on a light
   surface is invisible rather than merely wrong. Backgrounds stay unset so
   cards and controls keep their own. */
window.ctx-window label,
window.ctx-window button,
window.ctx-window entry {
    color: @ctx_on_surface;
}

.ctx-header {
    background-color: @ctx_card;
    border-bottom: 1px solid @ctx_border;
    padding: 6px 8px;
    min-height: 40px;
}
.ctx-header-title {
    font-weight: bold;
}

/* Transparent rather than the surface colour: the card behind it already
   paints that, and painting it twice compounds the alpha — a translucent
   surface came out noticeably more solid wherever a page sat on it. */
.ctx-page {
    background-color: transparent;
}

.ctx-group-title {
    font-weight: bold;
    font-size: 1.05em;
    margin-left: 4px;
}
.ctx-group-description {
    font-size: 0.9em;
    opacity: 0.65;
    margin-left: 4px;
    margin-bottom: 2px;
}

/* One card per group, with the rows divided by a line rather than by
   separator widgets — a hidden row then leaves no gap behind it. */
.ctx-card {
    background-color: @ctx_card;
    border: 1px solid @ctx_border;
    border-radius: 12px;
}
.ctx-card > row {
    border-bottom: 1px solid @ctx_border;
    background: transparent;
}
.ctx-card > row:last-child {
    border-bottom: none;
}

/* Controls have to be styled explicitly now that no widget library is doing
   it. Kept to one shade and one hover, so a theme stays two colours to edit. */
/* Controls must be able to shrink with the sidebar. The default themes set a
   min-width on entries and dropdown buttons that is wider than a collapsed
   launcher, which pushes them off the right edge instead of narrowing them. */
window.ctx-window entry,
window.ctx-window spinbutton,
window.ctx-window spinbutton text,
window.ctx-window dropdown,
window.ctx-window dropdown > button {
    min-width: 0;
}
window.ctx-window dropdown > button > box > label {
    min-width: 0;
}

/* Scoped to the window rather than to `.ctx-page`, which reaches the settings
   page only: the sidebar's search box is not on it, so it kept the desktop
   theme's dark entry on a light surface. */
window.ctx-window button,
window.ctx-window entry,
window.ctx-window spinbutton,
window.ctx-window dropdown > button {
    background-image: none;
    background-color: @ctx_control;
    color: @ctx_on_surface;
    border: 1px solid @ctx_border;
    border-radius: 8px;
}
window.ctx-window button:hover,
window.ctx-window dropdown > button:hover {
    background-color: @ctx_control_hover;
}

/* `.linked` is not a GTK4 built-in. It comes from whatever stylesheet is in
   play — libadwaita's, or an Adwaita-derived desktop theme — and Context ships
   its own sheet with libadwaita removed, so it has to define the class itself
   or a linked box is just buttons that happen to touch.

   Both the position and the scope are load-bearing, and getting either wrong
   fails silently. The rule above gives every button in a Context window its
   own 8px plate; a `.linked > button` rule has the same specificity as
   `window.ctx-window button` (one class, two elements), so written earlier in
   the file it lost the tie and the corners stayed round. Written here, after
   it, and scoped to the window as well, it wins on both counts.

   `margin: 0` matters too: a desktop theme puts margin on buttons, and a gap
   between them is precisely what stops a group reading as one control.

   A GtkStackSwitcher gets the same treatment: it is a linked group that does
   not carry the class, since GTK styles it by element name. */
window.ctx-window box.linked > button,
window.ctx-window box.linked > entry,
window.ctx-window stackswitcher > button {
    border-radius: 0;
    margin: 0;
}
window.ctx-window box.linked > *:first-child,
window.ctx-window stackswitcher > button:first-child {
    border-top-left-radius: 8px;
    border-bottom-left-radius: 8px;
}
window.ctx-window box.linked > *:last-child,
window.ctx-window stackswitcher > button:last-child {
    border-top-right-radius: 8px;
    border-bottom-right-radius: 8px;
}
/* One border between neighbours rather than each drawing its own, which at
   this size is the difference between a join and a gap. */
window.ctx-window box.linked > *:not(:first-child),
window.ctx-window stackswitcher > button:not(:first-child) {
    border-left-width: 0;
}
window.ctx-window entry:focus-within,
window.ctx-window spinbutton:focus-within {
    border-color: @ctx_accent;
}

/* A spin button is an entry with two buttons inside it, so the plate belongs
   to the spinbutton and the buttons inside must be flat — styling them as
   buttons too is what produced the gaps and the height mismatch: three
   separate plates, each with its own border and radius, sitting in a row. */
window.ctx-window spinbutton {
    padding: 0;
}
window.ctx-window spinbutton > text {
    background: none;
    border: none;
    min-height: 32px;
    padding-left: 8px;
}
window.ctx-window spinbutton > button {
    background: none;
    background-image: none;
    border: none;
    border-radius: 0;
    box-shadow: none;
    min-width: 32px;
    min-height: 32px;
    padding: 0;
    margin: 0;
    color: @ctx_on_surface;
}
window.ctx-window spinbutton > button:hover {
    background-color: @ctx_control_hover;
}

/* A switch reads as on or off at a glance, which needs the two states to
   differ in more than a shade — the desktop theme's unchecked switch is very
   close to the card it sits on. */
window.ctx-window switch {
    background-color: @ctx_control_hover;
    border: 1px solid @ctx_border;
    border-radius: 14px;
    min-width: 44px;
    min-height: 24px;
}
window.ctx-window switch:checked {
    background-color: @ctx_accent;
    border-color: @ctx_accent;
}
window.ctx-window switch > slider {
    background-color: @ctx_card;
    border: 1px solid @ctx_border;
    border-radius: 50%;
    min-width: 20px;
    min-height: 20px;
    margin: 1px;
}

window.ctx-window checkbutton check {
    background-color: @ctx_control;
    border: 1px solid @ctx_border;
    border-radius: 5px;
    min-width: 18px;
    min-height: 18px;
}
window.ctx-window checkbutton check:checked {
    background-color: @ctx_accent;
    border-color: @ctx_accent;
    color: @ctx_surface;
}

.ctx-status-title {
    font-weight: bold;
    font-size: 1.2em;
}
.ctx-status-description,
.ctx-status-icon {
    opacity: 0.6;
}

.ctx-tile {
    background-color: @ctx_tile_background;
    border: 1px solid @ctx_tile_background;
    border-radius: 10px;
}
.ctx-tile:hover {
    background-color: @ctx_tile_hover;
}
.ctx-tile.ctx-chosen {
    background-color: @ctx_tile_selected;
    border-color: @ctx_accent;
}

/* One of several, chosen. */
.ctx-choice:checked {
    box-shadow: inset 0 0 0 2px @ctx_accent;
}

/* A note's text. A bare GtkTextView paints the desktop theme's view colour,
   which on a Context surface is the one place the palette does not reach. */
.ctx-note-scroll {
    background-color: @ctx_tile_background;
    border: 1px solid @ctx_border;
    border-radius: 10px;
}
.ctx-note-body,
.ctx-note-body text {
    background-color: transparent;
    color: @ctx_on_surface;
    padding: 10px;
}

.ctx-rail-button {
    background-color: @ctx_rail_background;
    border: 2px solid transparent;
    border-radius: 12px;
    padding: 6px;
    min-width: 0;
    min-height: 0;
}
.ctx-rail-button:hover {
    background-color: @ctx_rail_hover;
}

/* Saved: dimmed and unfilled, so the running contexts read first. */
.ctx-rail-button.ctx-saved {
    opacity: 0.55;
}
.ctx-rail-button.ctx-saved:hover {
    opacity: 1;
}

/* Open: filled and at full strength. */
.ctx-rail-button.ctx-open {
    background-color: @ctx_rail_open;
    opacity: 1;
}

/* Current: filled harder and ringed in the accent. */
.ctx-rail-button.ctx-active {
    background-color: @ctx_rail_active;
    border-color: @ctx_accent;
    opacity: 1;
}

/* Nothing in the rail may set a floor above the configured width. */
.ctx-rail-toggle {
    min-width: 0;
    min-height: 0;
    padding: 2px;
}

.ctx-rail-divider {
    background-color: @ctx_rail_divider;
    margin: 4px 10px;
}

/* Settings rows stack their control under the description, so the text gets
   the full width and the control does too. */
.ctx-setting-title {
    font-weight: bold;
}
.ctx-setting-subtitle {
    font-size: 0.9em;
    opacity: 0.65;
}

/* A standalone GtkSpinButton already sizes its entry and its two buttons to
   match — measured at 34px each. Setting a min-height here does not: the rule
   reaches the entry but not the buttons, so it *creates* the mismatch it looks
   like it would fix. Leave the geometry to the theme and only give the control
   room to breathe. */
.ctx-spin {
    margin-top: 2px;
}
"""


_current: Theme | None = None
_installed = False
_provider = None
_user_provider = None
_monitor = None


def current() -> Theme:
    """The loaded theme, read once per run."""
    global _current
    if _current is None:
        _current = Theme.load()
    return _current


def reload() -> Theme:
    global _current
    _current = Theme.load()
    return _current


def install() -> bool:
    """Put the stylesheets on the display, once, and watch style.css.

    Anything using a `ctx-` style class has to call this — the launcher styles
    its rail, the editor its tiles, and whichever appears first must not be the
    unstyled one.

    Both providers sit *above* USER, not at it. GTK4 ignores `gtk-theme-name`,
    so the usual way to get a theme is `~/.config/gtk-4.0/gtk.css` importing it
    — which is what home-manager writes — and GTK loads that file at USER. A
    desktop theme therefore arrives at Context's own priority rather than at
    THEME beneath it, and a rule tied with it is decided by whatever the
    tie-break happens to be. That is not a contest to enter: `.linked` was
    defined, present in the sheet, and silently lost to Mint-Y for exactly this
    reason. The built-in sheet goes one step above the imported theme, and
    style.css one above that, so the order is theme, then Context, then the
    user — which is what it always claimed to be.
    """
    global _installed, _provider, _user_provider
    if _installed:
        return True

    from gi.repository import Gdk, Gtk

    display = Gdk.Display.get_default()
    if display is None:
        return False

    _provider = Gtk.CssProvider()
    _provider.load_from_data(current().css())
    Gtk.StyleContext.add_provider_for_display(
        display, _provider, Gtk.STYLE_PROVIDER_PRIORITY_USER
    )

    _user_provider = Gtk.CssProvider()
    # A mistake in the file should name the line in the log, not vanish.
    _user_provider.connect(
        "parsing-error",
        lambda _p, section, error: log.warning(
            "style.css: %s (%s)", error.message, section.to_string()
        ),
    )
    _load_user_css()
    Gtk.StyleContext.add_provider_for_display(
        display, _user_provider, Gtk.STYLE_PROVIDER_PRIORITY_USER + 1
    )

    _watch()
    _installed = True
    return True


def _load_user_css() -> None:
    _user_provider.load_from_data(style_text().encode())


def _watch() -> None:
    """Re-style on save, the way Hyprland reloads its own config."""
    global _monitor
    from gi.repository import Gio

    gfile = Gio.File.new_for_path(str(style_path()))
    _monitor = gfile.monitor_file(Gio.FileMonitorFlags.NONE, None)
    _monitor.connect("changed", _on_style_changed)


def _on_style_changed(_monitor, _file, _other, event) -> None:
    from gi.repository import Gio

    # Editors save in bursts; the hint is the burst ending. CREATED covers a
    # first save, DELETED an rm — which restores the defaults.
    if event in (
        Gio.FileMonitorEvent.CHANGES_DONE_HINT,
        Gio.FileMonitorEvent.CREATED,
        Gio.FileMonitorEvent.DELETED,
    ):
        log.info("style.css changed; restyling")
        reinstall()


def reinstall() -> bool:
    """Reload both stylesheets in place, for when style.css changes."""
    reload()
    if not _installed:
        return install()
    _provider.load_from_data(current().css())
    _load_user_css()
    return True
